[package]
name = "disjoint"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.14", features = ["full", "extra-traits", "visit", "visit-mut"]}
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.56"
rustc-hash = "1.1.0"
quote = "1.0.26"
